name: GdUnit4 Tests
on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: "4.3"
          godot-status: "stable"
          paths: "ticket-to-rio/test"
          publish-report: false
          report-name: test_report