name: "godot-ci export"
on:
  push:
    branches:
      - 49-add-artifact-in-release # Your current testing branch
  pull_request:
    branches:
      - 49-add-artifact-in-release # Your current testing branch

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: ticket-to-rio
  PROJECT_PATH: ticket-to-rio

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-22.04 # Use 22.04 with godot 4
    container:
      image: barichello/godot-ci:4.3
    permissions: # <-- Add this permissions block
      contents: write   # Required to create releases (create tags and upload assets)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Godot Templates and Config
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/godot/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          if [ -d "/root/.config/godot" ]; then
            mv /root/.config/godot/* ~/.config/godot/ 2>/dev/null || true
          else
            echo "Notice: /root/.config/godot not found, skipping move."
          fi

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)" 
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      
      - name: Upload Build Artifact (Workflow)
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.sha }}
          path: build/windows/${{ env.EXPORT_NAME }}.exe

      - name: Create GitHub Release and Upload Asset
        # This condition will create a release on pushes to your '49-add-artifact-in-release' branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/49-add-artifact-in-release' 
        uses: softprops/action-gh-release@v2
        with:
          files: build/windows/${{ env.EXPORT_NAME }}.exe
          name: "Build from ${{ github.ref_name }} - ${{ github.sha }}"
          tag_name: "build-${{ github.ref_name }}-${{ github.sha }}"
          body: |
            Automated build from branch ${{ github.ref_name }}.
            Commit: ${{ github.sha }}
            Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          draft: false
          prerelease: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}